# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

posts = [
  {
    title: "OPENBIKE: A BICICLETA QUE VOCÊ PODE 'BAIXAR' E MONTAR DE GRAÇA",
    body: "As bicicletas estão entre os meios de transporte mais sustentáveis que existem — precisam apenas da nossa força para andar e não emitem CO2. Porém, sua fabricação (e o transporte das peças e do produto) ainda consomem muitos recursos naturais. Para resolver esse problema e tornar as bikes ainda mais sustentáveis, um estúdio de design do País Basco (parte da Espanha) começou a trabalhar no projeto OpenBike em 2017. A ideia, da dupla de designers do Arquimaña, é uma bicicleta que pode ser fabricada em qualquer lugar do mundo — o projeto tem licença Creative Commons e qualquer um pode baixá-lo no site. O principal material usado é madeira compensada, um recurso renovável. O estúdio Arquimaña dá todas as instruções para quem quiser montar sua própria OpenBike, em qualquer lugar do mundo. É claro que você precisa comprar o material e pagar alguém com uma máquina CNC para cortar a madeira — de modo que a bike não sai realmente de graça. O “preço”, no fim das contas, sai “elas por elas”, em comparação com uma bike comum. Ainda assim, quem escolhe a OpenBike elimina as emissões de carbono da fabricação e transporte (que não são poucas), tendo uma bicicleta bem mais sustentável e moderna.",
    user_id: 1
  },
  {
    title: "6 MILAGRES DA MEDICINA QUE PERMANECEM SEM EXPLICAÇÃO",
    body: "Apesar das tecnologias de ponta, conhecimentos milenares e profissionais cada vez mais especializados, a medicina ainda é capaz de surpreender as pessoas, entregando mistérios sem revelação e casos que parecem não apenas desafiar as leis da física, mas as próprias questões básicas da vida humana. Ao longo da história, a área exibiu situações estranhas e com reviravoltas macabras, supondo que uma força sobrenatural brincava com as condições de pacientes sem qualquer motivo aparente. Confira abaixo alguns dos mais bizarros casos da medicina que permanecem sem explicação até hoje. Em 2008, o jovem Jordan Taylor, de apenas nove anos na época, sofreu um acidente de carro e acabou sendo infligido pela condição de decapitação interna — luxação atlanto-occipital —, quando seu crânio e coluna se separaram, mas a cabeça permaneceu ligada ao corpo pelos tecidos. Segundo estatísticas, 70% das pessoas afetadas por esse grau de decapitação morrem na hora, enquanto 28% morrem em poucas horas e 2% sobrevivem com paralisia perpétua, mas o garoto se recuperou totalmente em três meses e saiu sozinho do hospital.",
    user_id: 1
  },
  {
    title: "MULTIDÕES QUE MATAM: 3 EPISÓDIOS MAIS MORTAIS DA HISTÓRIA",
    body: "Para que multidões se tornem mais mortais que um automóvel em alta velocidade, é preciso apenas de dois fatores: superlotação e desespero. Por vezes, o excesso de pessoas se torna apenas um agravante em meio ao caos que pode desencadear quando os indivíduos se sentem ameaçados por algum motivo. No último 5 de novembro, tivemos uma representação disso durante o festival Astroworld, comandado pela estrela do rap Travis Scott, que reuniu no NRG Park, em Houston (Texas, EUA) uma plateia de 100 mil pessoas. No entanto, a gama de problemas e negligências aconteceu bem antes de os visitantes cruzarem os portões do local. A arena escolhida para sediar o evento já era conhecida por dezenas de problemas de hiperlotação e, somados com falta de segurança e de suporte necessários para o primeiro evento dessa magnitude realizado nos Estados Unidos desde o início da pandemia, ele se tornou uma bomba com os minutos contados para explodir. Horas antes do início do show, milhares de pessoas conseguiram entrar no local por diversas brechas menosprezadas pela produção, diminuindo ainda mais o espaço já escasso. Meia hora depois de Scott ter subido ao palco, às 21h30, as primeiras pessoas foram dadas como mortas por conta do caos que se instalou no local. Pessoas presentes disseram que drogas em seringas estavam sendo aplicadas involuntariamente nas pessoas, além das brigas por espaço e empurra-empurra. O resultado foram, pelo menos, 8 pessoas mortas, com idades entre 14 e 27 anos, e milhares ficaram feridas no local. “Foi um inferno”, disse Nick Johson, 17, em depoimento ao The New York Times. “Todo mundo que estava atrás tentava correr para frente do palco”. Mas isso não foi nada em comparação aos desastres que já aconteceram envolvendo multidões.",
    user_id: 1
  },
  {
    title: "Friends: como seria se Chandler terminasse a série com Janice?",
    body: "Por meio de um vídeo divertido compartilhado pelo TikTok e, posteriormente, pelo Instagram, a atriz Maggie Wheeler, que interpretou Janice no seriado Friends, brincou com a possibilidade de sua personagem terminar a série ao lado de Chandler Bing (interpretado por Matthew Perry). Criando uma nova versão para a icônica abertura do show, a composição é interpretada pela dona do perfil jaxwritessongs. “Ninguém nunca falou sobre o único erro de Friends”, introduz a letra. “O melhor casal da série nunca chegou ao fim. Chandler e Monica ficaram bem juntos, mas eu acho que Chandler deveria ter terminado com outra pessoa”, continua a música. Confira o vídeo completo abaixo! Apesar de não ter participado da maioria dos episódios, assim como Gunther (de James Michael Tyler), Janice se tornou uma das figuras mais lembradas da produção transmitida pela NBC entre 1994 e 2004. Vale lembrar, nesse sentido, que ela foi introduzida logo na 1ª temporada como a namorada um tanto quanto irritante do personagem em questão. Talvez por conta de sua voz aguda e desagradável, Chandler não se orgulhava tanto em namorar com Janice. E conforme visto durante vários episódios, ele tentou romper esse relacionamento indesejado por algumas vezes, mas sempre voltava atrás em sua decisão inicial por conta dos sentimentos de Janice. Quem se lembra dela caindo no choro quando tinha alguma conversa mais profunda com o namorado? No entanto, com o passar do tempo, Janice foi ficando cada vez mais em segundo plano, até que Chandler desenvolveu um grande afeto por Monica (Courtney Cox), com ambos se apaixonando na 5ª temporada e apresentando ao público alguns dos momentos mais hilários e românticos da série. O casal em questão forma uma família na última temporada, algo que, inevitavelmente, se configuraria de outra forma caso Janice tivesse continuado seu relacionamento com Chandler. Apesar dos dois não terem ficado juntos, esse fator foi decisivo para o divertimento dos fãs, que reencontraram Janice em um novo contexto no intitulado “The One Where Estelle Dies”. Pensando sobre especulações, certamente Chandler também se modificaria completamente ao lado de Janice, algo que talvez não fosse tão interessante assim. Mas e você? O que acharia se Chandler e Janice tivessem terminado a série juntos?",
    user_id: 1
  },
  {
    title: "Pix substitui dinheiro em três de cada quatro transações",
    body: "Na última quinta-feira (25), o diretor de inovação, produtos e serviços da Federação Brasileira dos Bancos (Febraban), Leandro Vilain, anunciou que três a cada quatro transações via Pix substituem pagamentos que teriam sido realizados em dinheiro, caso o sistema não existisse. Dados das instituições financeiras apontam que 1,2 bilhão de transferências via Pix foram efetuadas somente no mês de outubro. Destas, 900 milhões estariam substituindo interações com dinheiro físico. Em 12 meses, a ferramenta teve uma grande adesão por parte da população e já apresenta mudanças no mercado com seus erros e acertos. “Eu fico imaginando como o digital transformou a vida das pessoas, que teriam que manusear esse dinheiro, perderiam tempo para isso”, disse Vilain em uma conferência online promovida pela Febraban. Segundo Vilain, somente em 2020, os bancos investiram R$ 25 bilhões em inovações tecnológicas e pretendem seguir dedicando verbas para garantir um dos sistemas mais sofisticados do mundo. “Temos 70 milhões de pessoas já com dados biométricos coletados, e este é só um dos nossos avanços”, enfatiza. Nesta segunda-feira (29), a plataforma de pagamentos recebeu duas novas modalidades de uso, o “Pix Saque” e o “Pix Troco”. No entanto, uma das principais preocupações ainda é a segurança digital. Segundo o especialista, o aumento de vazamentos de dados, que pode ser observado em todo o mundo, é um custo que agrega para o sistema, não só pelo gasto com a fraude, mas a despesa com a prevenção. Confira como funciona, por exemplo, o 'Golpe do Pix' e como proteger seus dados, nesta matéria.",
    user_id: 1
  },
  {
    title: "Zelda: Ocarina of Time ganha recriação de rara demo de 1997",
    body: "Quase 25 anos depois de tirar o fôlego dos visitantes da Space World em 1997, a primeira demo pública de The Legend of Zelda: Ocarina of Time — ou uma versão bastante fiel da original — está sendo recriada por um grupo de fãs da série da Nintendo. Esqueça os populares Directs gravados e exibidos no YouTube: na Space World, os visitantes podiam testar em primeira mão os games que a Big N estava preparando. Como foi o caso de Zelda: Ocarina of Time e sua mítica demo de 1997, até então \"perdida\" — ou mais ou menos isso. Utilizando arquivos encontrados \"por acaso\", um grupo de jogadores conseguiu recriar a demonstração de Zelda OoT o mais próxima o possível daquela versão lendária vista na Space World. O feito só foi alcançado graças ao colecionador conhecido como Forest of Illusion, que no começo deste ano pôs as mãos em um cartucho de F-Zero X com 32 MB de espaço utilizado. O fato é que este jogo normalmente só precisava de metade desta quantidade de armazenamento, o que levou a uma inspeção dos arquivos contidos no cartucho e a descoberta de arquivos da demo perdida de Ocarina of Time. De posse desses 16 MB de arquivos do protótipo, o grupo foi capaz de extrair informações suficientes para recriar uma versão muito próxima da demo apresentada pela Nintendo na Space World ’97. Embora não seja reconstrução exata, agora finalmente será possível ter um gostinho da experiência vivida pelos visitantes da feira na década de 1990.",
    user_id: 1
  },
  {
    title: "Dying Light 2 deve pesar 21 GB no PS5 antes do patch de primeiro dia",
    body: "Dying Light 2, depois de muitos adiamentos, deve ser lançado em 4 de fevereiro para diversas plataformas. Se você pretende jogar no PS5, já pode ir garantindo 21 GB livres até lá, segundo uma mineração de dados do jogo. O tweet acima vem da PlayStation Game Size, que usa um robô para tentar descobrir quanto vai pesar cada jogo no Play antes do lançamento. A conta tem um bom histórico de acertos, mas é bem importante destacar que, antes da estreia de um game, ela consegue revelar apenas quanto ele vai pesar sem o famoso patch de primeiro dia. Já faz uns bons anos que praticamente todo game lançado recebe um patch de primeiro dia, trazendo as últimas melhorias e aparos de arestas que os devs completaram depois de enviar a primeira versão do jogo para distribuição. Esse update não costuma impactar muito no tamanho final dos jogos. O tweet nos informa também que o pre-load para Dying Light 2 deve ser liberado em 2 de fevereiro, dois dias antes de seu lançamento. A conta foca no PlayStation, mas é seguro imaginar que a data vai valer para o PC, os Xbox e o Switch, onde o jogo também será lançado. Com a data de pre-load e o peso no PS5 revelados, é difícil que o game sofra mais adiamentos, mas com seu histórico, não dá pra dizer que é impossível.",
    user_id: 1
  }
]

common_user = User.new(username: 'Commom User', email: 'user@user.com', password: '123456', password_confirmation: '123456')
anonymous_user = User.new(username: 'Anonymous/Anonimo', email: 'anonymous@user.com', password: '654321', password_confirmation: '654321')

common_user.save!
anonymous_user.save!

posts.each do |post|
  Post.new(post).save!
end

